### ISSUE TITLE
Testing Jibril independent of Github Actions

### ISSUE THREAD

**Issue by kousiktn** [listendev/jibril-releases#1]
Is it possible to run the Jibril loader outside of the Github Actions? If I just run the loader from the releases page, I get errors around missing eBPF objects (which makes sense).

```
╠ WARN  ╣     ebpfobjs ◂PKG ┃ FILE▸      handlers.go ┃    71  ┃ FUNC▸                 initComp ┃▸ no eBPF objects found
╠ WARN  ╣         ebpf ◂PKG ┃ FILE▸      handlers.go ┃    23  ┃ FUNC▸                 initComp ┃▸ no eBPF objects found
```

Will the eBPF object files that the loader uses also be released with the release package?

I am also curious about the new architecture that Jibril uses (this was why I wanted to test it in the first place) and the part about never missing events.
From the docs at https://listendev.github.io/jibril/dev/overview/history/, my understanding is that Jibril doesn't send events back to userspace but rather stores it in Kernel space and makes it available later through a query language (which the user agent can then use). Is that interpretation correct? If so, where is the event related data stored in the Kernel (is that achieved through a Kernel module?)

Thanks and apologies if this isn't the right place to ask about this!

**Comment by rafaeldtinoco** [comment]
Could you share how you're running it ? The no eBPF found message is likely because you haven't selected any extension to run. 

You can try with a config file (like described at `https://listendev.github.io/jibril/dev/usage/usage/`) or directly in the cmdline by doing something like:

```
sudo -E <binary> --extension config --extension example --plugin example:helloworld
```

To test things up. And to run a specific logic:

```
sudo -E <binary> --extension config --extension jibril --plugin jibril:hold --plugin jibril:detect --event jibril:detect:file_example --printer jibril:printers:stdout
```

The `file_example` logic will detect `sudo touch /tmp/blergh` for example (for you to check if its working).

In the cmdline you can then enable any detection event you want:

  - jibril:detect:capabilities_modification
  - jibril:detect:code_modification_through_procfs
  - jibril:detect:core_pattern_access
  - jibril:detect:cpu_fingerprint
  - jibril:detect:credentials_files_access
  - jibril:detect:file_example
  - jibril:detect:filesystem_fingerprint
  - jibril:detect:java_debug_lib_load
  - jibril:detect:java_instrument_lib_load
  - jibril:detect:machine_fingerprint
  - jibril:detect:os_fingerprint
  - jibril:detect:os_network_fingerprint
  - jibril:detect:os_status_fingerprint
  - jibril:detect:package_repo_config_modification
  - jibril:detect:pam_config_modification
  - jibril:detect:sched_debug_access
  - jibril:detect:shell_config_modification
  - jibril:detect:ssl_certificate_access
  - jibril:detect:sudoers_modification
  - jibril:detect:sysrq_access
  - jibril:detect:unprivileged_bpf_config_access
  - jibril:detect:code_on_the_fly
  - jibril:detect:denial_of_service_tools
  - jibril:detect:exec_example
  - jibril:detect:exec_from_unusual_dir
  - jibril:detect:file_attribute_change
  - jibril:detect:hidden_elf_exec
  - jibril:detect:net_filecopy_tool_exec
  - jibril:detect:net_mitm_tool_exec
  - jibril:detect:net_scan_tool_exec
  - jibril:detect:net_sniff_tool_exec
  - jibril:detect:net_suspicious_tool_exec
  - jibril:detect:net_suspicious_tool_shell
  - jibril:detect:passwd_usage
  
  Or you can detect flows only:
  
  - jibril:net:flow

Or both, etc. Do not enable `jibril:github` plugin and you will be fine. The stdout printer is going to show in stdout, there is also a `varlog` printer (among others). 

I hope it helps.

NOTE: About storing in kernel and using a query language: yes, instead of exploring ring buffers approach (either with ebpf perf/ring buffers) - like I criticized in my past works (https://www.youtube.com/watch?v=xdEVGT5vAIM) - we have different mechanisms like in-kernel logic (userland independent) and userland querying. We plan to open-source parts of it (or most of it) in a near future, but we're still finishing core parts development first.

**Comment by kousiktn** [comment]
Thanks a lot for the response! I am able to actually run it now (I missed the documentation page previously and was simply just running the binary to see what it does). Passing the flags documented above seems to get it to work and seems like the bpf objects are baked into the binary (this certainly makes shipping the binary a whole lot easy!).

This maybe a bit obvious but BPF load failed on `5.15` version of the Kernel complaining that the BPF program was too large. I guess the older verifier is stricter? However I was able to get it running on `6.8` kernel version.

Are there any config options to list all detect and fire (for the lack of a better word) an event to stdout for all file accesses of all processes on the machine? I just wanted to stress test that aspect of it :)

> NOTE: About storing in kernel and using a query language: yes, instead of exploring ring buffers approach (either with ebpf perf/ring buffers) - like I criticized in my past works (https://www.youtube.com/watch?v=xdEVGT5vAIM) - we have different mechanisms like in-kernel logic (userland independent) and userland querying. We plan to open-source parts of it (or most of it) in a near future, but we're still finishing core parts development first.

That's certainly very interesting and very cool! I would be very interested to see the architecture there when it is open sourced. Thanks again for your response!

**Comment by rafaeldtinoco** [comment]
> This maybe a bit obvious but BPF load failed on `5.15` version of the Kernel complaining that the BPF program was too large. I guess the older verifier is stricter? However I was able to get it running on `6.8` kernel version.

I had it working in 5.13 and beyond but I have not added multiple kernel versions (and x64/aarch64) to our CI/CD yet (like I did to tracee for example). I'm currently running it in ~6.6, but I have this in my backlog. Making it to work in ~5.13 will likely be okay (due to CO-RE features, maybe even 5.9, if verifier of those kernels help a bit).

> Are there any config options to list all detect and fire (for the lack of a better word) an event to stdout for all file accesses of all processes on the machine? I just wanted to stress test that aspect of it :)

I see where you are going :P =).

The detection recipes have limits on amount of similar detections made to the same process (or binary, or thread, etc, depending on the detection) for example, but it would be possible to write a recipe to do what you want very easily (not sure I will due to our GA phase).

Either way, we might have something better than that. I'm releasing soon a graph of the resources and actions taken on each resource. You will be able to expand task -> files -> actions or file -> tasks -> actions, or task -> net flow -> metadata or net flow -> tasks -> metadata (you got the point).

This graph will be represented in a yaml file from a printer, so might satisfy your needs. 

Maybe you can share more details of your needs and intent and I'll probably feel more inclined to provide you a feature or something like that. 

Best regards and thanks for the feedback.

**Comment by kousiktn** [comment]
> Either way, we might have something better than that. I'm releasing soon a graph of the resources and actions taken on each resource. You will be able to expand task -> files -> actions or file -> tasks -> actions, or task -> net flow -> metadata or net flow -> tasks -> metadata (you got the point).

Oh this will be amazing!

> Maybe you can share more details of your needs and intent and I'll probably feel more inclined to provide you a feature or something like that.

I'm really just playing around with eBPF for getting more observability - I've looked at using tracee but have been thinking about the question of "how can I assert that I won't miss an event from the syscalls / kprobes I'm tracing?". And so Jibril's documentation around event-less architecture and slowing down a monitored function until the event can be processed and stored was very appealing!

Thanks again for the discussion here. I'll keep my eyes open for when you open source Jibril. Cheers!

**Comment by rafaeldtinoco** [comment]
> I'm really just playing around with eBPF for getting more observability - I've looked at using tracee but have been thinking about the question of "how can I assert that I won't miss an event from the syscalls / kprobes I'm tracing?". And so Jibril's documentation around event-less architecture and slowing down a monitored function until the event can be processed and stored was very appealing!

Cool! Nice to hear that. Just a quick fix, Jibril is not delaying the execution of syscalls (its overhead is 0.2% in syscalls) and it is still keeping track of things, just thought that could be nice to know. Cheers!

**Comment by kousiktn** [comment]
> Just a quick fix, Jibril is not delaying the execution of syscalls (its overhead is 0.2% in syscalls) and it is still keeping track of things, just thought that could be nice to know. Cheers!

Got it - I think I understand the architecture a lot better now (I also recently came across BPF iterators which put some things into context and hashmaps, which explained the rest). Btw, is there a discord chat I could join to follow along? The link in docs.listen.dev appears broken (or I don't have permissions, likely by design, in which case its self-explanatory!).

**Comment by rafaeldtinoco** [comment]
> Btw, is there a discord chat I could join to follow along? The link

https://listendev.github.io/jibril/dev/ and https://docs.listen.dev/ are working for me (without any special privilege). Not for you ?

Yep, you can find our public discord channels at: https://discord.com/invite/BYywucg8

**Comment by kousiktn** [comment]
Sorry, I meant the discord link in https://docs.listen.dev (https://discord.com/invite/BYywucg8) is broken (https://docs.listen.dev works!). I get 
![Screenshot 2024-12-18 at 3 40 57 PM](https://github.com/user-attachments/assets/c4fab579-a8c7-416b-b394-3d74b5048e0a)

**Comment by jadoonf** [comment]
@kousiktn looks like the last link auto-expired, here's the working one: https://lstn.dev/community

We're putting together dedicated public channel for community discussions like this. Thank you for your feedback, and stay tuned from updates from our side!

**Comment by jadoonf** [comment]
We now have a new place for this: https://github.com/listendev/jibril-releases/discussions cc @umar-sik @rafaeldtinoco
